### ISSUE TITLE
Modprobe together with start script

### ISSUE THREAD

**Issue by imrehg** [soracom/resin-rpi-demo#1]
Looking at the current implementation of `CMD`, there are [two of them listed](https://github.com/soracom/resin-rpi-demo/blob/ac368721473b9df695b66c967d0bbdd49cdf248f/Dockerfile.template#L20-L22), but that should be incorrect to my knowledge.

Instead it should probably be combined as:

```dockerfile
CMD modprobe i2c-dev && bash start.sh
```

**Comment by alexissusset** [comment]
Thank you @imrehg 

Updated the project and removed modprobe as it's not used in this example
