### ISSUE TITLE
usb_modswitch required?

### ISSUE THREAD

**Issue by nickd0** [soracom/resin-rpi-demo#2]
Trying this out and unable to get a signal with a Huawei E3531. From the status light it looks like the device might not be in modem mode. Should the mode switching be handled automatically?
On a raspbian image I was able to get a signal when I use usb_modeswitch with network manager, but not out of the box.

**Comment by ssshah86** [comment]
try the resin forums, https://forums.resin.io/t/using-usb-modeswitch-to-enable-4g-usb-modem/554

or the docs, which specifically reference your modem: https://forums.resin.io/t/using-usb-modeswitch-to-enable-4g-usb-modem/554

**Comment by alexissusset** [comment]
From latest testing, there's no need for usb_modeswitch in ResinOS 2.x as most Modems are already supported by embedded Network / Modem Manager

Should your modem not be supported, the best way is to write udev_rules, here's an example in this repo:
https://github.com/alexissusset/soracom-resin-modemAT/tree/f718037e6f5b09451e78f068f5eb892c6458e138/udev-rules

I'll close this issue as it seems that everything is resolved now.
